name: Release

on:
  release:
    types: [ published ]

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      SIGNING_RING: ${{ secrets.SIGNING_RING }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
      - name: Grant permission
        run: chmod +x gradlew
      - run: echo "version=$tag" > buildSrc/version.properties
        env:
          tag: ${{ github.event.release.tag_name }}
      - name: Encode gpg
        run: echo -n "$SIGNING_RING" | base64 --decode > private.gpg
      - name: echo signing.properties
        run: echo -e "signing.keyId=${SIGNING_KEY_ID}\nsigning.password=${SIGNING_PASSWORD}\nsigning.secretKeyRingFile=${GITHUB_WORKSPACE}/private.gpg\nsonatypeUsername=${SONATYPE_USERNAME}\nsonatypePassword=${SONATYPE_PASSWORD}" > buildSrc/signing.properties
      - run: ./gradlew publishCentralPublicationToCentralRepository